#!/bin/bash -e

shippable_retry() {
  for i in $(seq 1 3);
  do
    {
      "$@"
      ret=$?
      [ $ret -eq 0 ] && break;
    } || {
      echo "retrying $i of 3 times..."
      echo "$@"
    }
  done
  return $ret
}

shippable_retry "$@"
